name: Publish Pelican Website

on:
  push:
    branches: [ main ]  # Trigger on every push to main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # Needed to push to gh-pages

    steps:
    # 1️⃣ Checkout the repo
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    # 2️⃣ Set up Python 3.11
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # 3️⃣ Install dependencies if requirements.txt exists
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install ghp-import pelican

    # 4️⃣ Build and deploy using Makefile
    - name: Publish site
      run: |
        make github