name: Publish Pelican Blog

# Trigger workflow only on content changes
on:
  push:
    branches: [ main ]
    paths:
      - 'content/**'
      - 'content/pages/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to push to gh-pages

    steps:
      # Checkout the repository with submodules
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Build and deploy the site
      - name: Build and publish
        run: |
          make github

